  version: '3'
    
  services:
    envoy:
      ports:
        - "10000:10000"
        - "9901:9901"
      build:
        context: .
        dockerfile: Dockerfile-envoy
    grpc-api:
      ports:
        - "50051:50051"
      build:
        context: .
        dockerfile: Dockerfile-grpc